---
- hosts: all
  become: True
  tasks:
    - name: Install python pip
      apt:
        name: python-pip
        state: present
    - name: Start the container
      docker_container:
        name: kgovinda
        image: "kgovinda/143:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
